// Brand new typeorm 0.3.x ormconfig.ts generator
import { configService } from './Config/Config.service';
import fs from 'fs';

// https://github.com/typeorm/typeorm/issues/8814#issuecomment-1149271688
const CONFIG_HEAD = `// This file is auto-generated by src/scripts/typeorm030-write-ormconfigts.ts
import { DataSource, DataSourceOptions } from 'typeorm';
export const connectionSource = new DataSource(
`;
const CONFIG_TAIL = ` as DataSourceOptions);
`;

const ORM_CONFIG = 'ormconfig.ts';
if (fs.existsSync(ORM_CONFIG)) {
  fs.unlinkSync(ORM_CONFIG);
}
fs.writeFileSync(
  ORM_CONFIG,
  CONFIG_HEAD +
    JSON.stringify(configService.getTypeormDataSourceOptions(), null, 2) +
    CONFIG_TAIL,
);